### PR TITLE
Deprecation of RHEL 6 / CentOS 6

### PR DESCRIPTION
**Pull request by amanda11**
Remove running of CI jobs for EL6.

addressing st2ci - remove EL6 from StackStorm/discussions#39

### CODE REVIEW

**Comment by amanda11** [comment]
There were a few points in these files I didn't quite understand. EL8 didn't seem to be in, so I put in EL8. But if there's some reason for EL8 not being in then good to understand why:

- actions/workflows/promote_package.yaml
- actions/promote_package.yaml
- aliases/promote_package.yaml

**Comment by amanda11** [comment]
@blag is there any follow-up required for the EL6 removal? Or can this be merged?

**Comment by blag** [comment]
No follow up required. Thanks for your contribution!

**Comment by armab** [comment]
@blag @punkrokk Can someone please ensure that updated version of `st2ci` is deployed on a live server?

**Comment by punkrokk** [comment]
@armab Done

**Pull request merged**
