### PR TITLE
CI improvements

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by Kami** [comment]
Looks like this PR is already deployed on the CI servers so let's please also merge it to avoid confusion and out of date scenario.

Not being merge confused me today when debugging some build issues.

**Comment by Kami** [comment]
I pushed a fix in 545d19be40678e175527c07943f194a2283b99ee.

It looks like that recently Github started posting Webhooks for pull requests where "branch" is actually set to pull request name and not branch name. This seems wrong from the Github side, but it causes Circle CI build failures on our side so we should also filter those events out.

Here is an example of wrongly set "branch" from our CI server:

```bash
tomaz@st2-build-node-1:~$ st2 execution get 58788cb727263a06f5274050
id: 58788cb727263a06f5274050
action.ref: st2ci.build_pkgs
parameters: 
  branch: pull/3159
  circle_url: https://circleci.com/gh/StackStorm/st2/2785
  commit_message: Removed unnecessary comment
  committer: Matt Oswalt
  deploy_packages: false
  github_url: None
  revision: f297bb472e829afde42b9bfa27981f4428d28f14
status: succeeded (18s elapsed)
start_timestamp: 2017-01-13T08:15:51.224366Z
end_timestamp: 2017-01-13T08:16:09.277448Z
```

**Comment by Kami** [comment]
I will also go ahead and merge this into master because changes are already deployed on the CI server otherwise it will just cause more confusion.

**Comment by enykeev** [comment]
This was likely not a problem with Github posting webhooks, but with us changing when CircleCI builds are supposed to be started. in https://github.com/StackStorm/st2/commit/bd88049795cb5e66961832cb03c8f6113a3080d3, it would previously only run CircleCI for merged changes implicitly stating that the owner of the repo should be StackStorm. By removing the section and not specifying owner explicitly, we ended up in a situation when Circle is executed for forks too.

What we need to figure out now is how much of our machinery we want to leave exposed to outside collaborators. Place where you cut it out for now is a good one. With it, PR's only get most basic CI being done for the changes (units, lints and stuff). With some additional modifications, we can let it build packages for PR's too, but then we need to assume that some packages in CircleCI artifacts may end up containing malicious code (reasonable assumption given we have decent introspection into the code and build pipeline). Whether we want to automatically run this presumably malicious code during e2e runs is entirely different question.

**Comment by enykeev** [comment]
As for having st2ci master out of sync with build server master, I'm not really comfortable merging code without an extra pair of eyes and we currently have no way of running another build server in parallel to the production one so here we are. Some of you stumbling on it, reviewing the code and merging it was essentially the plan all along =) You did review the code, don't you?

**Pull request merged**
